"""
Reads a checkpoint saved by train.py and writes
components/tlm_core/src/tlm_weights_data.c — a single flat byte array
that gets reinterpret-cast to `const TlmWeights*` in tlm_model.c.

The write order below MUST match the field order in tlm_model.h's
TlmWeights / TlmLayerWeights structs exactly, field for field. If you
add/reorder/resize a field in tlm_model.h, mirror the change here.

Usage:
    python export_weights.py --ckpt tlm32.pt --out ../components/tlm_core/src/tlm_weights_data.c
"""
import argparse
import numpy as np
import torch

from tlm_torch import TLM32, N_LAYERS

# NOTE: order below mirrors tlm_model.h's TlmWeights struct field-for-field.


def t2b(tensor):
    """torch tensor -> little-endian float32 bytes, row-major, no transpose."""
    return tensor.detach().cpu().numpy().astype("<f4").tobytes()


def export(state_dict, out_path):
    model = TLM32()
    model.load_state_dict(state_dict)
    model.eval()

    blob = bytearray()
    blob += t2b(model.token_embedding)  # [VOCAB][EMBED]
    blob += t2b(model.pos_embedding)    # [CONTEXT_LEN][EMBED]

    for i in range(N_LAYERS):
        blk = model.blocks[i]
        blob += t2b(blk.ln1_w)
        blob += t2b(blk.ln1_b)
        blob += t2b(blk.wq)
        blob += t2b(blk.wk)
        blob += t2b(blk.wv)
        blob += t2b(blk.wo)
        blob += t2b(blk.ln2_w)
        blob += t2b(blk.ln2_b)
        blob += t2b(blk.w1)
        blob += t2b(blk.b1)
        blob += t2b(blk.w2)
        blob += t2b(blk.b2)

    blob += t2b(model.final_ln_w)
    blob += t2b(model.final_ln_b)
    blob += t2b(model.output_w)
    blob += t2b(model.output_b)

    return bytes(blob)


def write_c_array(blob, out_path):
    with open(out_path, "w") as f:
        f.write('/* AUTO-GENERATED by tools/export_weights.py — do not hand-edit.\n')
        f.write(' * Reinterpreted as `const TlmWeights*` in tlm_model.c.\n')
        f.write(' */\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'const uint32_t g_tlm_weights_blob_len = {len(blob)}u;\n')
        f.write('const uint8_t g_tlm_weights_blob[] __attribute__((aligned(4))) = {\n')
        for i in range(0, len(blob), 20):
            chunk = blob[i:i + 20]
            f.write('    ' + ', '.join(str(b) for b in chunk) + ',\n')
        f.write('};\n')
    print(f"Wrote {len(blob):,} bytes ({len(blob)/1024:.1f} KB) to {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", type=str, default="tlm32.pt")
    ap.add_argument("--out", type=str, default="../components/tlm_core/src/tlm_weights_data.c")
    ap.add_argument("--bin", type=str, default=None, help="optionally also dump raw .bin (for the host test harness)")
    args = ap.parse_args()

    state_dict = torch.load(args.ckpt, map_location="cpu")
    blob = export(state_dict, args.out)
    write_c_array(blob, args.out)
    if args.bin:
        with open(args.bin, "wb") as f:
            f.write(blob)
        print(f"Also wrote raw binary to {args.bin}")


if __name__ == "__main__":
    main()
